version: '3'

services:

  wordpress:
    build: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_PASSWORD: example
      WORDPRESS_DB_HOST: maria

  maria:
    build: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example

